#!/usr/bin/env python3


import os
import subprocess
import shutil


if __name__ == '__main__':
    export_dir = 'export'
    os.makedirs(export_dir, exist_ok=True)
    os.chdir(export_dir)

    if os.name == 'nt':
        subprocess.run(['python', '-m', 'venv', '.venv'], check=True)
        subprocess.run(['.venv\\Scripts\\pip.exe', 'install', '-r', '..\\requirements.txt'], check=True)
    else:
        subprocess.run(['python3', '-m', 'venv', '.venv'], check=True)
        subprocess.run(['.venv/bin/pip3', 'install', '-r', '../requirements.txt'], check=True)

    img_proc_dir = os.path.join('scripts', 'img_proc')
    os.makedirs(img_proc_dir, exist_ok=True)
    os.makedirs('assets', exist_ok=True)
    os.makedirs('save', exist_ok=True)

    img_proc_files = os.listdir(os.path.join('..', img_proc_dir))
    for file in img_proc_files:
        if file.endswith('.py'):
            src_path = os.path.join('..', img_proc_dir, file)
            dst_path = os.path.join(img_proc_dir, file)
            shutil.copy2(src_path, dst_path)
